#! /bin/bash

assetDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "mv $@" >> $assetDir/mock-log-file.txt

# copy mock chromedriver instead of move
if [[ "$2" == "/usr/local/bin" ]]; then
  /bin/cp "$assetDir/mock-chromedriver" "$2/chromedriver"
fi